# Generated by Django 3.2.7 on 2021-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20211122_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='observation',
            field=models.IntegerField(verbose_name='Обсервация'),
        ),
    ]
