# Generated by Django 3.2.7 on 2022-02-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_fee',
            field=models.DecimalField(decimal_places=20, max_digits=30, verbose_name='Оплата в час'),
        ),
    ]
