# Generated by Django 3.2.7 on 2022-02-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_profile_hourly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_fee',
            field=models.CharField(max_length=5, verbose_name='Оплата в час'),
        ),
    ]
