# Generated by Django 3.2.7 on 2022-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_auto_20220223_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='days_road',
            field=models.FloatField(verbose_name='Дни в пути'),
        ),
    ]
