# Generated by Django 3.2.7 on 2022-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_alter_profile_days_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='days_road',
            field=models.IntegerField(verbose_name='Дни в пути'),
        ),
    ]
