# Generated by Django 3.2.7 on 2021-09-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='holiday',
        ),
    ]
