# Generated by Django 3.2.7 on 2021-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20211122_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Обсервация',
        ),
        migrations.AddField(
            model_name='profile',
            name='observation',
            field=models.IntegerField(default=0, verbose_name='Обсервация'),
        ),
    ]
