# Generated by Django 3.2.7 on 2021-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_profile_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='month',
            field=models.IntegerField(default=0, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Месяц'),
            preserve_default=False,
        ),
    ]
