# Generated by Django 3.2.7 on 2022-02-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_profile_hourly_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hourly_fee',
            field=models.FloatField(verbose_name='Оплата в час'),
        ),
    ]
