# Generated by Django 3.2.7 on 2022-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0017_alter_results_days_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='all_result',
            field=models.FloatField(verbose_name='Начислено'),
        ),
        migrations.AlterField(
            model_name='results',
            name='award',
            field=models.FloatField(verbose_name='Премия'),
        ),
        migrations.AlterField(
            model_name='results',
            name='district_coefficient',
            field=models.FloatField(verbose_name='Районный коэффициент'),
        ),
        migrations.AlterField(
            model_name='results',
            name='extras',
            field=models.FloatField(verbose_name='Доплата за вахту'),
        ),
        migrations.AlterField(
            model_name='results',
            name='holiday',
            field=models.FloatField(verbose_name='Доплата за праздники'),
        ),
        migrations.AlterField(
            model_name='results',
            name='northern_coefficient',
            field=models.FloatField(verbose_name='Северный коэффициент'),
        ),
        migrations.AlterField(
            model_name='results',
            name='observation',
            field=models.FloatField(verbose_name='Обсервация'),
        ),
        migrations.AlterField(
            model_name='results',
            name='result',
            field=models.FloatField(verbose_name='На руки'),
        ),
        migrations.AlterField(
            model_name='results',
            name='wage',
            field=models.FloatField(verbose_name='Оклад'),
        ),
    ]
